"""initial schema

Revision ID: 6a3caaf9eb26
Revises: 
Create Date: 2026-07-08 21:25:55.851641

"""
from alembic import op
import sqlalchemy as sa


revision = '6a3caaf9eb26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_tr', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('typical_portion_g', sa.Float(), nullable=True),
    sa.Column('typical_portion_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_name_tr'), 'foods', ['name_tr'], unique=True)
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_lists_week_start'), 'shopping_lists', ['week_start'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('onboarding_state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('body_composition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_composition_logs_ts'), 'body_composition_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_body_composition_logs_user_id'), 'body_composition_logs', ['user_id'], unique=False)
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('neck_cm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_measurements_ts'), 'body_measurements', ['ts'], unique=False)
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summarized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_ts'), 'conversation_messages', ['ts'], unique=False)
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activity', sa.String(length=120), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_logs_ts'), 'exercise_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_exercise_logs_user_id'), 'exercise_logs', ['user_id'], unique=False)
    op.create_table('food_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_food_pref_user_name')
    )
    op.create_index(op.f('ix_food_preferences_user_id'), 'food_preferences', ['user_id'], unique=False)
    op.create_table('hunger_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=True),
    sa.Column('craving', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hunger_logs_ts'), 'hunger_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_hunger_logs_user_id'), 'hunger_logs', ['user_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('diet_strategy', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_meal_plans_week_start'), 'meal_plans', ['week_start'], unique=False)
    op.create_table('memory_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_notes_user_id'), 'memory_notes', ['user_id'], unique=False)
    op.create_table('mood_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_logs_ts'), 'mood_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_mood_logs_user_id'), 'mood_logs', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('start_weight_kg', sa.Float(), nullable=True),
    sa.Column('goal_weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('neck_cm', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=32), nullable=True),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('daily_movement', sa.String(length=255), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('diseases', sa.String(length=1000), nullable=True),
    sa.Column('has_diabetes', sa.Boolean(), nullable=False),
    sa.Column('has_thyroid', sa.Boolean(), nullable=False),
    sa.Column('has_insulin_resistance', sa.Boolean(), nullable=False),
    sa.Column('has_hypertension', sa.Boolean(), nullable=False),
    sa.Column('has_cholesterol', sa.Boolean(), nullable=False),
    sa.Column('has_digestive_issues', sa.Boolean(), nullable=False),
    sa.Column('allergies', sa.String(length=1000), nullable=True),
    sa.Column('intolerances', sa.String(length=1000), nullable=True),
    sa.Column('medications', sa.String(length=1000), nullable=True),
    sa.Column('supplements', sa.String(length=1000), nullable=True),
    sa.Column('surgeries', sa.String(length=1000), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('exercise_types', sa.JSON(), nullable=True),
    sa.Column('exercise_frequency_per_week', sa.Integer(), nullable=True),
    sa.Column('exercise_duration_min', sa.Integer(), nullable=True),
    sa.Column('eats_breakfast', sa.Boolean(), nullable=False),
    sa.Column('eats_lunch', sa.Boolean(), nullable=False),
    sa.Column('eats_dinner', sa.Boolean(), nullable=False),
    sa.Column('eats_snacks', sa.Boolean(), nullable=False),
    sa.Column('eats_outside', sa.String(length=255), nullable=True),
    sa.Column('coffee_per_day', sa.Integer(), nullable=True),
    sa.Column('tea_per_day', sa.Integer(), nullable=True),
    sa.Column('water_glasses_per_day', sa.Integer(), nullable=True),
    sa.Column('alcohol', sa.String(length=255), nullable=True),
    sa.Column('smoking', sa.String(length=255), nullable=True),
    sa.Column('cooking_skill', sa.String(length=32), nullable=True),
    sa.Column('kitchen_equipment', sa.JSON(), nullable=True),
    sa.Column('monthly_food_budget', sa.String(length=120), nullable=True),
    sa.Column('shopping_preferences', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('progress_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_photos_ts'), 'progress_photos', ['ts'], unique=False)
    op.create_index(op.f('ix_progress_photos_user_id'), 'progress_photos', ['user_id'], unique=False)
    op.create_table('reminder_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_settings_user_id'), 'reminder_settings', ['user_id'], unique=False)
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_items_list_id'), 'shopping_items', ['list_id'], unique=False)
    op.create_table('sleep_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_logs_ts'), 'sleep_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_sleep_logs_user_id'), 'sleep_logs', ['user_id'], unique=False)
    op.create_table('steps_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_logs_ts'), 'steps_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_steps_logs_user_id'), 'steps_logs', ['user_id'], unique=False)
    op.create_table('target_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('carb_g', sa.Integer(), nullable=False),
    sa.Column('fiber_g', sa.Integer(), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.Column('diet_strategy', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_history_effective_date'), 'target_history', ['effective_date'], unique=False)
    op.create_index(op.f('ix_target_history_user_id'), 'target_history', ['user_id'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_logs_ts'), 'water_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_water_logs_user_id'), 'water_logs', ['user_id'], unique=False)
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_logs_ts'), 'weight_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_weight_logs_user_id'), 'weight_logs', ['user_id'], unique=False)
    op.create_table('planned_meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('recipe', sa.String(length=4000), nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carb_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('shared_with_partner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_meals_plan_id'), 'planned_meals', ['plan_id'], unique=False)
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carb_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('is_cheat', sa.Boolean(), nullable=False),
    sa.Column('planned_meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planned_meal_id'], ['planned_meals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_logs_ts'), 'meal_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_meal_logs_user_id'), 'meal_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_logs_user_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_ts'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_planned_meals_plan_id'), table_name='planned_meals')
    op.drop_table('planned_meals')
    op.drop_index(op.f('ix_weight_logs_user_id'), table_name='weight_logs')
    op.drop_index(op.f('ix_weight_logs_ts'), table_name='weight_logs')
    op.drop_table('weight_logs')
    op.drop_index(op.f('ix_water_logs_user_id'), table_name='water_logs')
    op.drop_index(op.f('ix_water_logs_ts'), table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index(op.f('ix_target_history_user_id'), table_name='target_history')
    op.drop_index(op.f('ix_target_history_effective_date'), table_name='target_history')
    op.drop_table('target_history')
    op.drop_index(op.f('ix_steps_logs_user_id'), table_name='steps_logs')
    op.drop_index(op.f('ix_steps_logs_ts'), table_name='steps_logs')
    op.drop_table('steps_logs')
    op.drop_index(op.f('ix_sleep_logs_user_id'), table_name='sleep_logs')
    op.drop_index(op.f('ix_sleep_logs_ts'), table_name='sleep_logs')
    op.drop_table('sleep_logs')
    op.drop_index(op.f('ix_shopping_items_list_id'), table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index(op.f('ix_reminder_settings_user_id'), table_name='reminder_settings')
    op.drop_table('reminder_settings')
    op.drop_index(op.f('ix_progress_photos_user_id'), table_name='progress_photos')
    op.drop_index(op.f('ix_progress_photos_ts'), table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_mood_logs_user_id'), table_name='mood_logs')
    op.drop_index(op.f('ix_mood_logs_ts'), table_name='mood_logs')
    op.drop_table('mood_logs')
    op.drop_index(op.f('ix_memory_notes_user_id'), table_name='memory_notes')
    op.drop_table('memory_notes')
    op.drop_index(op.f('ix_meal_plans_week_start'), table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_hunger_logs_user_id'), table_name='hunger_logs')
    op.drop_index(op.f('ix_hunger_logs_ts'), table_name='hunger_logs')
    op.drop_table('hunger_logs')
    op.drop_index(op.f('ix_food_preferences_user_id'), table_name='food_preferences')
    op.drop_table('food_preferences')
    op.drop_index(op.f('ix_exercise_logs_user_id'), table_name='exercise_logs')
    op.drop_index(op.f('ix_exercise_logs_ts'), table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_ts'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_ts'), table_name='body_measurements')
    op.drop_table('body_measurements')
    op.drop_index(op.f('ix_body_composition_logs_user_id'), table_name='body_composition_logs')
    op.drop_index(op.f('ix_body_composition_logs_ts'), table_name='body_composition_logs')
    op.drop_table('body_composition_logs')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shopping_lists_week_start'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_foods_name_tr'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
